Opetushallitus/konfo-ui

src/main/app/public/locales/fi/translation.json, src/main/app/src/assets/css/styles.css, src/main/app/src/components/koulutus/Ammatillinen.js, src/main/app/src/components/koulutus/AvoinYo.js, src/main/app/src/components/koulutus/Korkeakoulu.js, src/main/app/src/components/koulutus/KoulutusInfoBoxTwoSided.js, src/main/app/src/components/koulutus/Lukiokoulutus.js, src/main/app/src/tools/Utils.js
Näytetään kaksipuolisessa infolaatikossa koulutukselle kaikki aktiiviset hakuajat sekä hakunappula (joka ei tee tässä vaiheessa mitään), jos aktiivisia on. Jos ei ole, näytetään seuraavaksi alkava hakuaika jos sellainen on tiedossa sekä muistutusnappula (funktionaalisuus puuttuu toki tästäkin).
Toistaiseksi tuo komponentti on lisätty vasta korkeakoulukoulutusten sivuille.
=> Kto 41 - Haun tiedot koulutukselle

src/main/app/public/locales/fi/translation.json, src/main/app/src/components/common/HtmlTextBox.js, src/main/app/src/components/koulutus/Koulutus.js, src/main/app/src/reducers/koulutusSlice.js
- amm koulutuksen kuvauksen hakeminen eperuste id:n perusteella komo-sivulla
- kuvauksen muotoilu komo-sivulla, jos se koostuu tutkinnon suorittaneen osaamisesta ja työtehtävistä
=> KTO-605 ja KTO-699

src/main/app/src/components/Preview.js, src/main/app/src/components/koulutus/Koulutus.js, src/main/app/src/components/toteutus/Toteutus.js, src/main/app/src/store/reducers/koulutusSlice.js, src/main/app/src/stores/rest-store.js
Bugin korjaus on tässä tiedostossa:
src/main/app/src/components/koulutus/Koulutus.js
Muut tiedostot:
* en lisännyt yksikkötestejä koska oli poistuvaa toteutusta
* rest-store + Preview -tiedostoihin korjasin Eslint herjat, jotta ne eivät tule startissa.
* muutin myös selectKoulutus + selectJarjestajat currytetyiksi jotta useSelectorissa ei tarvitse tehdä erillistä lambdaa
=> KTO-892: Removed HakuKaynnissaCard + small refactoring

src/main/app/src/components/toteutus/Toteutus.js, src/main/app/src/components/toteutus/ToteutusHakukohteet.js, src/main/app/src/store/reducers/toteutusSlice.js
* Korjattu isHakuEndInFuture ja isHakuAuki logiikat
* Selectorit currytetyiks niin ei tarvi lambdaa hookissa e.g. (state) => asioita
Näille sliceille ois kiva kirjottaa yksikkötestit (KoulutusSlicelle on jo) mutta niiden ajelun korjaus tais olla ton 862 osana niin voisin naputella niitä siinä kohta sit ku se on masterissa.
=> KTO-912: fix showing not-ending hakukohteet

src/main/app/src/store/reducers/koulutusSlice.js
Status oli undefined === ei tehty koskaan mitään tuleville järjestäjille
=> hotfix KOMO page tulevat jarjestajat

src/main/app/cypress/mocks/komoto-kuvaus-tooltip.mocks.json, src/main/app/cypress/mocks/komoto-osaamisala-kuvaus.mocks.json, src/main/app/cypress/mocks/komoto-osaamisala.mocks.json, src/main/app/cypress/mocks/komoto-tutkinnon-osa.mocks.json, src/main/app/cypress/mocks/murupolku.mocks.json, src/main/app/src/components/toteutus/ToteutusInfoGrid.tsx, src/main/app/src/types/ToteutusTypes.ts
- koulutuksenAlkamiskausiUUSI -> koulutuksenAlkamiskausi
=> KTO-1119: Rename koulutuksen alkamiskausi fields

src/main/app/src/components/oppilaitos/Yhteystiedot.tsx
Toteutus-sivulla voi olla listatty useiden oppilaitosten yhteystietoja, jotka voivat olla samoja. Yhteystiedot-komponentille annettu id pitää ottaa aina mukaan OskariKartalle välitettävään id:een.
=> Korjattu yhteystietojen OskariKartta-komponentin id-attribuuttia

src/main/app/public/index.html, src/main/app/src/App.js, src/main/app/src/colors.ts, src/main/app/src/components/Etusivu.tsx, src/main/app/src/components/common/ContentWrapper.js, src/main/app/src/components/common/Header.js, src/main/app/src/components/common/HtmlTextBox.js, src/main/app/src/components/palaute/PalautePopup.js, src/main/app/src/components/sivu/LinkOrYoutube.js, src/main/app/src/components/sivu/Sisalto.js, src/main/app/src/components/sivu/Sivu.js, src/main/app/src/hooks.js, src/main/app/src/theme.js
Sisältää tiketit
https://jira.eduuni.fi/browse/OY-3136
https://jira.eduuni.fi/browse/OY-3759
https://jira.eduuni.fi/browse/OY-3224
https://jira.eduuni.fi/browse/OY-3225
https://jira.eduuni.fi/browse/OY-3631
https://jira.eduuni.fi/browse/OY-3237
Pari on vielä testattavana, mutta puhuttiin dailyssä että on ok katselmoida ja viedä tämä eteenpäin
=> Fix title to youtube embedded video

src/main/app/public/locales/fi/translation.json, src/main/app/src/components/laskuri/graafi/GraafiContainer.tsx, src/main/app/src/components/laskuri/graafi/PisteGraafi.tsx
https://jira.eduuni.fi/browse/OY-4073
=> Add missing localization for hakukohde select

src/main/app/cypress/integration/komoto-pistelaskuri.spec.js, src/main/app/public/locales/fi/translation.json, src/main/app/src/components/laskuri/Keskiarvo.test.ts, src/main/app/src/components/laskuri/Keskiarvo.ts, src/main/app/src/components/laskuri/KeskiarvoLaskuri.tsx, src/main/app/src/components/laskuri/KeskiarvoTulos.tsx, src/main/app/src/components/laskuri/ResultSphere.tsx, src/main/app/src/components/laskuri/aine/KeskiarvoAineLaskuri.tsx, src/main/app/src/components/laskuri/aine/Kouluaine.ts, src/main/app/src/components/laskuri/common/SuorittanutCheckbox.tsx
https://jira.eduuni.fi/browse/OY-4001
=> Oy 4001 suorittanut laskuri

src/main/app/cypress/integration/komoto-pistelaskuri.spec.js, src/main/app/public/locales/fi/translation.json, src/main/app/src/components/laskuri/Keskiarvo.test.ts, src/main/app/src/components/laskuri/Keskiarvo.ts, src/main/app/src/components/laskuri/KeskiarvoTulos.tsx, src/main/app/src/components/laskuri/ResultSphere.tsx
https://jira.eduuni.fi/browse/OY-4079
=> Oy 4079 osalaskut

src/main/app/src/components/valintaperusteet/Sisalto.tsx
https://jira.eduuni.fi/browse/OY-4076
=> OY-4076: Style TableContainer in valintaperusteet

src/main/app/src/components/sivu/TableOfContents.js
=> OY-3045: Sivun sisällysluettelon tyylikorjaus

src/main/app/src/components/common/OskariKartta.tsx, src/main/app/src/components/oppilaitos/OppilaitosOsaList.js, src/main/app/src/components/oppilaitos/OppilaitosPage.js, src/main/app/src/components/oppilaitos/Yhteystiedot.tsx, src/main/app/src/components/oppilaitos/hooks.ts, src/main/app/src/components/toteutus/ToteutuksenYhteystiedot.tsx, src/main/app/src/types/common.ts
https://jira.eduuni.fi/browse/OPHJOD-50
Vaatii toimiakseen kunnolla myös https://jira.eduuni.fi/browse/OPHJOD-50
=> Oy 3593 toimipisteet hierarkia support

src/main/app/src/components/suodattimet/hakutulosSuodattimet/KoulutusalaSuodatin.tsx
https://jira.eduuni.fi/browse/OY-4270
=> Enable showing counts to koulutusalat

src/main/app/src/api/konfoApi.ts, src/main/app/src/components/common/PageSection.tsx, src/main/app/src/components/sivu/SivuRouter.tsx, src/main/app/src/hooks/useContentful.ts, src/main/app/src/tools/slugUtils.test.ts, src/main/app/src/tools/slugUtils.ts, src/main/app/src/types/common.ts, src/main/app/src/types/contentful/TypeSivu.ts
Enable seamless language changes between fi/sv and en site pages via new optional Contentful field englishPageVersionId.
=> OY-3589 Contentful space links

src/main/app/public/locales/fi/translation.json, src/main/app/src/components/common/LanguageDropDown.tsx
Add visual focus indicator and screen reader label to the language selector in the header.
=> OY-4294 Language selector keyboard navi fix

src/main/app/package-lock.json, src/main/app/src/components/sivu/LinkOrYoutube.tsx
Avaa relatiiviset linkit samassa välilehdessä ja absoluuttiset uuteen välilehteen. Ikoni vain uuteen välilehteen avautuviin linkkeihin.
=> OY-4408 Open relative links in same tab

src/main/app/playwright/fixtures/search-hakukohteet.json, src/main/app/src/components/laskuri/VertaaHakukohteeseen.tsx, src/main/app/src/types/konfo-backend.d.ts
Luetaan hakukohteen järjestäjä tiedot uudesta kentästä jarjestyspaikkaEnriched
=> OY-4687 Hakukohteen tiedoissa ei näy organisaation nimeä pistelaskurin hakukohdevalikossa

src/main/app/src/components/sivu/SivuRouter.tsx
Lisätään puuttuva uudelleenohjaus
=> OY-5192 Lisätty yksi uusi maailmalle-sivustojen redirect
